package sdl

import (
	"github.com/tinogoehlert/go-sdl2/sdl"
	"github.com/tinogoehlert/goom/drivers"
)

var sdlKeyMap = map[sdl.Keycode]drivers.Keycode{
	sdl.K_UP:       drivers.KeyUp,
	sdl.K_LEFT:     drivers.KeyLeft,
	sdl.K_RIGHT:    drivers.KeyRight,
	sdl.K_DOWN:     drivers.KeyDown,
	sdl.K_SPACE:    drivers.KeySpace,
	sdl.K_KP_ENTER: drivers.KeyEnter,
	sdl.K_0:        drivers.Key0,
	sdl.K_1:        drivers.Key1,
	sdl.K_2:        drivers.Key2,
	sdl.K_3:        drivers.Key3,
	sdl.K_4:        drivers.Key4,
	sdl.K_5:        drivers.Key5,
	sdl.K_6:        drivers.Key6,
	sdl.K_7:        drivers.Key7,
	sdl.K_8:        drivers.Key8,
	sdl.K_9:        drivers.Key9,
	sdl.K_a:        drivers.KeyA,
	sdl.K_b:        drivers.KeyB,
	sdl.K_c:        drivers.KeyC,
	sdl.K_d:        drivers.KeyD,
	sdl.K_e:        drivers.KeyE,
	sdl.K_f:        drivers.KeyF,
	sdl.K_g:        drivers.KeyG,
	sdl.K_h:        drivers.KeyH,
	sdl.K_i:        drivers.KeyI,
	sdl.K_j:        drivers.KeyJ,
	sdl.K_k:        drivers.KeyK,
	sdl.K_l:        drivers.KeyL,
	sdl.K_m:        drivers.KeyM,
	sdl.K_n:        drivers.KeyN,
	sdl.K_o:        drivers.KeyO,
	sdl.K_p:        drivers.KeyP,
	sdl.K_q:        drivers.KeyQ,
	sdl.K_r:        drivers.KeyR,
	sdl.K_s:        drivers.KeyS,
	sdl.K_t:        drivers.KeyT,
	sdl.K_u:        drivers.KeyU,
	sdl.K_v:        drivers.KeyV,
	sdl.K_w:        drivers.KeyW,
	sdl.K_x:        drivers.KeyX,
	sdl.K_y:        drivers.KeyY,
	sdl.K_z:        drivers.KeyZ,
}

var driversKeyMap = map[drivers.Keycode]sdl.Keycode{
	drivers.KeyUp:     sdl.K_UP,
	drivers.KeyLeft:   sdl.K_LEFT,
	drivers.KeyRight:  sdl.K_RIGHT,
	drivers.KeyDown:   sdl.K_DOWN,
	drivers.KeySpace:  sdl.K_SPACE,
	drivers.KeyEnter:  sdl.K_KP_ENTER,
	drivers.KeyRShift: sdl.K_RSHIFT,
	drivers.KeyLShift: sdl.K_LSHIFT,
	drivers.Key0:      sdl.K_0,
	drivers.Key1:      sdl.K_1,
	drivers.Key2:      sdl.K_2,
	drivers.Key3:      sdl.K_3,
	drivers.Key4:      sdl.K_4,
	drivers.Key5:      sdl.K_5,
	drivers.Key6:      sdl.K_6,
	drivers.Key7:      sdl.K_7,
	drivers.Key8:      sdl.K_8,
	drivers.Key9:      sdl.K_9,
	drivers.KeyA:      sdl.K_a,
	drivers.KeyB:      sdl.K_b,
}
