package glfw

import (
	"github.com/go-gl/glfw/v3.2/glfw"
	"github.com/tinogoehlert/goom/drivers"
)

var glfwKeyMap = map[glfw.Key]drivers.Keycode{
	glfw.KeyUp:    drivers.KeyUp,
	glfw.KeyLeft:  drivers.KeyLeft,
	glfw.KeyRight: drivers.KeyRight,
	glfw.KeyDown:  drivers.KeyDown,
	glfw.KeySpace: drivers.KeySpace,
	glfw.KeyEnter: drivers.KeyEnter,
	glfw.Key0:     drivers.Key0,
	glfw.Key1:     drivers.Key1,
	glfw.Key2:     drivers.Key2,
	glfw.Key3:     drivers.Key3,
	glfw.Key4:     drivers.Key4,
	glfw.Key5:     drivers.Key5,
	glfw.Key6:     drivers.Key6,
	glfw.Key7:     drivers.Key7,
	glfw.Key8:     drivers.Key8,
	glfw.Key9:     drivers.Key9,
	glfw.KeyA:     drivers.KeyA,
	glfw.KeyB:     drivers.KeyB,
	glfw.KeyC:     drivers.KeyC,
	glfw.KeyD:     drivers.KeyD,
	glfw.KeyE:     drivers.KeyE,
	glfw.KeyF:     drivers.KeyF,
	glfw.KeyG:     drivers.KeyG,
	glfw.KeyH:     drivers.KeyH,
	glfw.KeyI:     drivers.KeyI,
	glfw.KeyJ:     drivers.KeyJ,
	glfw.KeyK:     drivers.KeyK,
	glfw.KeyL:     drivers.KeyL,
	glfw.KeyM:     drivers.KeyM,
	glfw.KeyN:     drivers.KeyN,
	glfw.KeyO:     drivers.KeyO,
	glfw.KeyP:     drivers.KeyP,
	glfw.KeyQ:     drivers.KeyQ,
	glfw.KeyR:     drivers.KeyR,
	glfw.KeyS:     drivers.KeyS,
	glfw.KeyT:     drivers.KeyT,
	glfw.KeyU:     drivers.KeyU,
	glfw.KeyV:     drivers.KeyV,
	glfw.KeyW:     drivers.KeyW,
	glfw.KeyX:     drivers.KeyX,
	glfw.KeyY:     drivers.KeyY,
	glfw.KeyZ:     drivers.KeyZ,
}

var driversKeyMap = map[drivers.Keycode]glfw.Key{
	drivers.KeyUp:     glfw.KeyUp,
	drivers.KeyLeft:   glfw.KeyLeft,
	drivers.KeyRight:  glfw.KeyRight,
	drivers.KeyDown:   glfw.KeyDown,
	drivers.KeySpace:  glfw.KeySpace,
	drivers.KeyEnter:  glfw.KeyEnter,
	drivers.KeyRShift: glfw.KeyRightShift,
	drivers.KeyLShift: glfw.KeyLeftShift,
	drivers.Key0:      glfw.Key0,
	drivers.Key1:      glfw.Key1,
	drivers.Key2:      glfw.Key2,
	drivers.Key3:      glfw.Key3,
	drivers.Key4:      glfw.Key4,
	drivers.Key5:      glfw.Key5,
	drivers.Key6:      glfw.Key6,
	drivers.Key7:      glfw.Key7,
	drivers.Key8:      glfw.Key8,
	drivers.Key9:      glfw.Key9,
	drivers.KeyA:      glfw.KeyA,
	drivers.KeyB:      glfw.KeyB,
	drivers.KeyC:      glfw.KeyC,
	drivers.KeyD:      glfw.KeyD,
	drivers.KeyE:      glfw.KeyE,
	drivers.KeyF:      glfw.KeyF,
	drivers.KeyG:      glfw.KeyG,
	drivers.KeyH:      glfw.KeyH,
	drivers.KeyI:      glfw.KeyI,
	drivers.KeyJ:      glfw.KeyJ,
	drivers.KeyK:      glfw.KeyK,
	drivers.KeyL:      glfw.KeyL,
	drivers.KeyM:      glfw.KeyM,
	drivers.KeyN:      glfw.KeyN,
	drivers.KeyO:      glfw.KeyO,
	drivers.KeyP:      glfw.KeyP,
	drivers.KeyQ:      glfw.KeyQ,
	drivers.KeyR:      glfw.KeyR,
	drivers.KeyS:      glfw.KeyS,
	drivers.KeyT:      glfw.KeyT,
	drivers.KeyU:      glfw.KeyU,
	drivers.KeyV:      glfw.KeyV,
	drivers.KeyW:      glfw.KeyW,
	drivers.KeyX:      glfw.KeyX,
	drivers.KeyY:      glfw.KeyY,
	drivers.KeyZ:      glfw.KeyZ,
}
